# frozen_string_literal: true
source "https://rubygems.org"
ruby "2.4.0"

gem 'sinatra', github: 'sinatra/sinatra'
gem 'sinja', github: 'mwpastore/sinja'
gem 'sinja-sequel', github: 'mwpastore/sinja-sequel'
gem 'sequel'
gem 'sequel_pg', require: 'sequel'
gem 'puma'

